kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./backend-nest/node_modules
        - ./client/node_modules

  - name: install-backend
    image: node
    environment:
      NODE_ENV: development
    commands:
      - cd backend-nest
      - npm install
    depends_on:
      - restore-cache

  - name: lint-backend
    image: node
    environment:
      NODE_ENV: development
    commands:
      - cd backend-nest
      - npm run lint
    depends_on:
      - install-backend

  - name: test-backend
    image: node
    environment:
      NODE_ENV: development
    commands:
      - cd backend-nest
      - npm run test
    depends_on:
      - install-backend

  - name: install-client
    image: node
    commands:
      - cd client
      - npm install
    depends_on:
      - restore-cache

  - name: lint-client
    image: node
    environment:
      NODE_ENV: development
    commands:
      - cd client
      - npm run lint
    depends_on:
      - install-client

  - name: build-client
    image: node
    environment:
      NODE_PATH: src/
      NODE_ENV: production
    commands:
      - cd client
      - npm run build
    depends_on:
      - install-client

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./backend-nest/node_modules
        - ./client/node_modules
    depends_on:
      - install-backend
      - install-client

volumes:
  - name: cache
    host:
      path: /tmp/cache
