version: "2.0"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=caspr
      - MYSQL_PASSWORD=caspr
      - MYSQL_DATABASE=caspr
    ports:
      - "3306:3306"
  backend:
    user: "${UID}:${GID}"
    build: ./backend
    command: npm run start
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
      - "4001:4001"
    depends_on:
      - mysql
  react:
    build: ./web-client
    command: yarn start
    environment:
      - NODE_ENV=development
    volumes:
      - ./web-client:/app
    ports:
      - "3000:3000"
      - "35729:35729"
  nginx:
    image: nginx
    volumes:
      - "./devops/dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "80:80"
    depends_on:
      - backend
      - react
    links:
      - backend
      - react
