version: '2.0'

services:
  postgresql:
    image: 'postgres:9.6.6'
    environment:
      - POSTGRES_USER=caspr
      - POSTGRES_PASSWORD=caspr
      - POSTGRES_DB=caspr
    ports:
      - '5432:5432'
  backend:
    build: ./backend
    command: yarn debug
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
      - "9229:9229"
    depends_on:
      - postgresql
  react:
    build: ./client
    command: yarn start
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
      - "35729:35729"
  nginx:
    image: nginx
    volumes:
      - './devops/dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - backend
      - react
    links:
      - backend
      - react
