---

- name: Install Nginx
  apt: name=nginx update_cache={{ update_apt_cache }} state=present

- name: Remove default site conf
  file: path=/etc/nginx/sites-available/default state=absent
  notify: reload nginx

- name: Create enhanced Diffie-Hellman parameters
  command: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Create the Nginx configuration file - Local
  template: src=nginx.conf.j2
            dest=/etc/nginx/sites-available/{{ project_name }}.conf
            backup=yes
  notify: reload nginx

- name: Ensure that the default site is disabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: Ensure that the application site is enabled
  file: src=/etc/nginx/sites-available/{{ project_name }}.conf
        dest=/etc/nginx/sites-enabled/{{ project_name }}.conf
        state=link
  notify: reload nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
